[nfs]
172.31.19.214 ansible_ssh_user='ec2-user'

[webservers]
172.31.22.170 ansible_ssh_user='ec2-user'
172.31.16.175 ansible_ssh_user='ec2-user'

[db]
172.31.16.207 ansible_ssh_user='ec2-user' 

[lb]
172.31.17.158 ansible_ssh_user='ubuntu'